plots:
  - Accuracy:
      x: step
      y:
        training/plots/metrics/train/acc.tsv: train/acc
        training/plots/metrics/test/acc.tsv: test/acc
      y_label: accuracy
  - Loss:
      x: step
      y:
        training/plots/metrics/train/loss.tsv: train/loss
        training/plots/metrics/test/loss.tsv: test/loss
      y_label: loss
  - Confusion matrix:
      template: confusion
      x: actual
      y:
        training/plots/sklearn/confusion_matrix.json: predicted
  - Actual vs Predicted:
      template: jitter.json
      x: actual
      y:
        training/plots/sklearn/confusion_matrix.json: predicted
  - hist.csv:
      x: preds
      y: digit
      template: bar_horizontal
      title: Histogram of Predictions
  - training/plots/images
stages:
  train:
    cmd: python train.py
    deps:
      - data
      - train.py
    params:
      - params.yaml:
    outs:
      - model.pt:
          checkpoint: true
      - training/plots:
          persist: true
      - hist.csv
    metrics:
      - training/metrics.json:
          persist: true
          cache: false
